---
apiVersion: acmecorp.com/v1alpha1
kind: App
metadata:
  name: sample-app
  namespace: default
spec:
  stack: stack.wasm
  image: stefanprodan/podinfo
  services:
    web:
      replicas: 2
    worker:
      env:
        LOG_LEVEL: trace
