---
apiVersion: acmecorp.com/v1alpha1
kind: App
metadata:
  name: sample-app
  namespace: default
spec:
  stack: stack.wasm
  image: stefanprodan/podinfo
  services:
    web:
      replicas: 2
    worker:
      env:
        LOG_LEVEL: trace

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-default
  namespace: argocd
spec:
  source:
    path: default/sample-app
    repoURL: http://git-repo-server.git-repo-server.svc.cluster.local:/git/manifests
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
