apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests.yaml
- git-clone-script.yaml
- argocd-app.yaml

images:
- name: controller
  newName: ghcr.io/shark/cd40-engine
  newTag: v0.0.1-develop.2

patches:
- path: deployment-patch.yaml
